package ssh

import "errors"

// SSH client errors
var (
	ErrSSHHostRequired       = errors.New("SSH host is required")
	ErrInvalidSSHPort        = errors.New("invalid SSH port (must be 1-65535)")
	ErrSSHUserRequired       = errors.New("SSH user is required")
	ErrSSHAuthRequired       = errors.New("SSH authentication method is required")
	ErrSSHConnectionFailed  = errors.New("SSH connection failed")
	ErrSSHTimeout           = errors.New("SSH operation timed out")
	ErrSSHCommandFailed     = errors.New("SSH command execution failed")
	ErrSSHSessionFailed     = errors.New("SSH session creation failed")
	ErrSSHClientClosed       = errors.New("SSH client is closed")
	ErrSSHConnectionClosed  = errors.New("SSH connection is closed")
	ErrSSHSessionClosed     = errors.New("SSH session is closed")
	ErrSSHNotConnected      = errors.New("SSH client is not connected")
	ErrSSHAlreadyConnected  = errors.New("SSH client is already connected")
	ErrSSHPoolFull         = errors.New("SSH connection pool is full")
	ErrSSHPoolEmpty         = errors.New("SSH connection pool is empty")
	ErrSSHConnectionNotFound = errors.New("SSH connection not found in pool")
	ErrSSHInvalidConnectionID = errors.New("invalid SSH connection ID")
	ErrSSHFileOperation     = errors.New("SSH file operation failed")
	ErrSSHUploadFailed       = errors.New("SSH file upload failed")
	ErrSSHDownloadFailed     = errors.New("SSH file download failed")
	ErrSSHKeyGeneration     = errors.New("SSH key generation failed")
	ErrSSHKeySave          = errors.New("SSH key save failed")
	ErrSSHKeyLoad          = errors.New("SSH key load failed")
	ErrSSHKeyParse         = errors.New("SSH key parse failed")
	ErrSSHInvalidKeyFormat  = errors.New("invalid SSH key format")
	ErrSSHKeyPermission     = errors.New("SSH key permission error")
	ErrSSHBastionFailed     = errors.New("SSH bastion connection failed")
	ErrSSHKnownHostsFailed  = errors.New("SSH known hosts operation failed")
	ErrSSHAuditFailed       = errors.New("SSH audit failed")
	ErrSSHSecurityIssue     = errors.New("SSH security issue found")
	ErrSSHInvalidAlgorithm  = errors.New("invalid SSH key algorithm")
	ErrSSHInvalidKeySize    = errors.New("invalid SSH key size")
	ErrSSHDuplicateKey      = errors.New("duplicate SSH key found")
	ErrSSHWeakKey          = errors.New("weak SSH key detected")
	ErrSSHOldKey           = errors.New("old SSH key detected")
	ErrSSHUnauthorized      = errors.New("SSH unauthorized access")
	ErrSSHForbidden         = errors.New("SSH forbidden access")
	ErrSSHNotFound          = errors.New("SSH resource not found")
	ErrSSHPermissionDenied  = errors.New("SSH permission denied")
)